### ISSUE TITLE
`ZeroDivisionError` when running `snapcraft login --with /home/circleci/.snapcraft.login` on CircleCi VM

### ISSUE THREAD

**Issue by amalota** [canonical/craft-cli#85]
We publish Snaps using CircleCi as part of our release CI flow. When trying to login to snapcraft in order to upload the snap we got the `ZeroDivisionError`. Here's the stacktrace:
 ```
+ snapcraft login --with /home/circleci/.snapcraft.login
Traceback (most recent call last):
  File "/snap/snapcraft/7710/bin/snapcraft", line 8, in <module>
    sys.exit(run())
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/snapcraft/cli.py", line 181, in run
    dispatcher.run()
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/dispatcher.py", line 406, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/snapcraft/commands/account.py", line 108, in run
    emit.message(
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 621, in func
    return wrapped_func(self, *args, **kwargs)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 725, in message
    self._printer.show(sys.stdout, text, use_timestamp=use_timestamp)  # type: ignore
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 374, in show
    self._show(msg)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 334, in _show
    self._write_line(msg)
  File "/snap/snapcraft/7710/lib/python3.8/site-packages/craft_cli/messages.py", line 279, in _write_line
    cleaner = " " * (usable - len(text) % width)
ZeroDivisionError: integer division or modulo by zero
```

We realised that the default size of the terminal was indeed columns=0 and rows=0. We managed to fixed it by setting the `COLUMNS` env variable to value different than 0. Here are some more information about the terminal that is being used by the CircleCi VM:
```
+ echo TERM=ansi
TERM=ansi
+ stty size
0 0
+ stty -a
speed 38400 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
+ export COLUMNS=1
+ COLUMNS=1
```

snapcraft version:
```
+ snapcraft --version
snapcraft 7.0.7
```

craft_cli version:
```
0.6.0
```

system
```
+ uname -a
Linux ip-172-28-43-116 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by facundobatista** [comment]
Probably we should treat a terminal with width 0 as not having a terminal at all...
